import { FormEvent, useEffect, useState } from 'react';
type Person = { id:number; name:string; age:number }; type Tx = { id:number; description:string; amount:number; type:'Income'|'Expense'; personId:number; personName:string; createdAt:string }; type Summary = { people:{personId:number;name:string;totalIncome:number;totalExpense:number;balance:number}[]; totalIncome:number; totalExpense:number; totalBalance:number };
const api = import.meta.env.VITE_API_URL || 'http://localhost:5184/api';
const money = (v:number) => new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v);
async function request(path:string, init?:RequestInit) { const r = await fetch(`${api}${path}`, { headers:{'Content-Type':'application/json'}, ...init }); if(!r.ok){ const b=await r.json().catch(()=>({})); throw new Error(b.message || 'Não foi possível concluir a operação.'); } return r.status===204 ? null : r.json(); }
export default function App(){
 const [people,setPeople]=useState<Person[]>([]), [transactions,setTransactions]=useState<Tx[]>([]), [summary,setSummary]=useState<Summary|null>(null), [message,setMessage]=useState(''), [person,setPerson]=useState({name:'',age:''}), [tx,setTx]=useState({description:'',amount:'',type:'Expense',personId:''});
 const load=async()=>{try{const [p,t,s]=await Promise.all([request('/people'),request('/transactions'),request('/summary')]);setPeople(p);setTransactions(t);setSummary(s)}catch(e){setMessage((e as Error).message)}}; useEffect(()=>{load()},[]);
 const savePerson=async(e:FormEvent)=>{e.preventDefault();try{await request('/people',{method:'POST',body:JSON.stringify({name:person.name,age:Number(person.age)})});setPerson({name:'',age:''});setMessage('Pessoa cadastrada com sucesso.');load()}catch(e){setMessage((e as Error).message)}};
 const saveTx=async(e:FormEvent)=>{e.preventDefault();try{await request('/transactions',{method:'POST',body:JSON.stringify({...tx,amount:Number(tx.amount),personId:Number(tx.personId)})});setTx({description:'',amount:'',type:'Expense',personId:''});setMessage('Transação cadastrada com sucesso.');load()}catch(e){setMessage((e as Error).message)}};
 const remove=async(id:number)=>{if(!confirm('Excluir esta pessoa e todas as transações dela?'))return;try{await request(`/people/${id}`,{method:'DELETE'});setMessage('Pessoa excluída.');load()}catch(e){setMessage((e as Error).message)}};
 return <main><header><h1>Controle de Gastos</h1><p>Organize as finanças da sua residência.</p></header>{message&&<div className="message">{message}<button onClick={()=>setMessage('')}>×</button></div>}
 <section className="grid"><article><h2>Pessoas</h2><form onSubmit={savePerson}><input required placeholder="Nome" value={person.name} onChange={e=>setPerson({...person,name:e.target.value})}/><input required min="0" max="150" type="number" placeholder="Idade" value={person.age} onChange={e=>setPerson({...person,age:e.target.value})}/><button>Cadastrar pessoa</button></form><table><thead><tr><th>Nome</th><th>Idade</th><th></th></tr></thead><tbody>{people.map(p=><tr key={p.id}><td>{p.name}</td><td>{p.age}</td><td><button className="danger" onClick={()=>remove(p.id)}>Excluir</button></td></tr>)}</tbody></table></article>
 <article><h2>Nova transação</h2><form onSubmit={saveTx}><input required placeholder="Descrição" value={tx.description} onChange={e=>setTx({...tx,description:e.target.value})}/><input required min="0.01" step="0.01" type="number" placeholder="Valor" value={tx.amount} onChange={e=>setTx({...tx,amount:e.target.value})}/><select value={tx.type} onChange={e=>setTx({...tx,type:e.target.value as 'Income'|'Expense'})}><option value="Expense">Despesa</option><option value="Income">Receita</option></select><select required value={tx.personId} onChange={e=>setTx({...tx,personId:e.target.value})}><option value="">Selecione a pessoa</option>{people.map(p=><option value={p.id} key={p.id}>{p.name} ({p.age} anos)</option>)}</select><button disabled={!people.length}>Cadastrar transação</button></form><small>Menores de 18 anos só podem cadastrar despesas.</small></article></section>
 <section><h2>Resumo financeiro</h2><div className="cards"><div>Receitas<strong>{money(summary?.totalIncome||0)}</strong></div><div>Despesas<strong>{money(summary?.totalExpense||0)}</strong></div><div>Saldo<strong>{money(summary?.totalBalance||0)}</strong></div></div><table><thead><tr><th>Pessoa</th><th>Receitas</th><th>Despesas</th><th>Saldo</th></tr></thead><tbody>{summary?.people.map(p=><tr key={p.personId}><td>{p.name}</td><td>{money(p.totalIncome)}</td><td>{money(p.totalExpense)}</td><td>{money(p.balance)}</td></tr>)}</tbody><tfoot><tr><td>Total geral</td><td>{money(summary?.totalIncome||0)}</td><td>{money(summary?.totalExpense||0)}</td><td>{money(summary?.totalBalance||0)}</td></tr></tfoot></table></section>
 <section><h2>Transações cadastradas</h2><table><thead><tr><th>Descrição</th><th>Pessoa</th><th>Tipo</th><th>Valor</th></tr></thead><tbody>{transactions.map(t=><tr key={t.id}><td>{t.description}</td><td>{t.personName}</td><td>{t.type==='Income'?'Receita':'Despesa'}</td><td>{money(t.amount)}</td></tr>)}</tbody></table></section></main> }
